ALTER TABLE school_settings ADD COLUMN IF NOT EXISTS teacher_report_card_access BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS student_id INTEGER;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS subject_id INTEGER;
